### ISSUE TITLE
IPAddress String usage

### ISSUE THREAD

**Issue by hreintke** [anakod/Sming#107]
I am working on my TelnetServer implementation and one of my debugf statements is : 
```
bool TelnetServer::telnetReceive (TcpClient& client, char *data, int size)
{
	debugf("TelnetServer callback : %s, %d bytes \r\n",client.getRemoteIp().toString().c_str(),size );
```
When compiling the sming framework with this I get the error : 
```
Wiring/IPAddress.h:26:7: error: forward declaration of 'class String'
 class String;
       ^
```
Updating in IPAdress.h : 
```
//class String;
#include "WString.h"
```
I can compile without errors.
Do you expect that this update will not influence other use of IPAddress of should I look for another solution.

**Comment by anakod** [comment]
You can include WString.h in your file, of course, but I think what this fix will be good to make usage more simple.

**Comment by anakod** [comment]
May be you will make P-R?

**Comment by hreintke** [comment]
OK, I will submit P-R
