### ISSUE TITLE
HTTPServer_WebSockets example not building

### ISSUE THREAD

**Issue by smitjj** [anakod/Sming#133]
Cannot build Websockets example, getting following error.

LD out/build/app.out
out/build/app_app.a(application.o):(.text._Z14startWebServerv+0x38): undefined reference to HttpServer::setWebSocketBinaryHandler(Delegate<void (WebSocket&, unsigned char*, unsigned int)>)' out/build/app_app.a(application.o): In functionDelegate':
/opt/Sming/Sming/SmingCore/Delegate.h:96: undefined reference to `HttpServer::setWebSocketBinaryHandler(Delegate<void (WebSocket&, unsigned char*, unsigned int)>)'
collect2: error: ld returned 1 exit status
make: * [out/build/app.out] Error 1

Any ideas?

**Comment by robotiko** [comment]
Same here with latest code from today .
Tested yesterday without issues.


2015-06-23 22:13 GMT+02:00 smitjj <notifications@github.com>:

**Comment by anakod** [comment]
Pease rebuild SmingFramework project.

**Comment by robotiko** [comment]
@anakod, 
I did but didn't solve the issue.

**Comment by anakod** [comment]
Try full SmingProject rebuild again please.

**Comment by robotiko** [comment]
Fixed!
Thanks a lot
