### ISSUE TITLE
HttpClient method typo  getReponseCode()  

### ISSUE THREAD

**Issue by robotiko** [anakod/Sming#160]
Shouldn't it be  getResponseCode()  reSponse with "S" instead of reponse?

**Comment by hreintke** [comment]
Sounds reasonable. I did a search through sming and example applications.
Only used in one example : MeteoControl.
We have two options : 
- remove the wrong named function and rename to correct
- add the correct function and after one/two releases remove the old, with mention this in release notes

@anakod : which option do you prefer?

**Comment by anakod** [comment]
I think it isn't big problem to rename it
