### ISSUE TITLE
Help wanted to complete WebSocket Client library and example for Sming

### ISSUE THREAD

**Issue by williamesp2015** [anakod/Sming#192]
Could you please complete Websocket with Client Library and example like https://github.com/krohling/ArduinoWebsocketClient.  I ported to Sming but needs more development (WebSocket2.zip in the https://files.gitter.im/alonewolfx2/Sming/Howl/WebSocket2.zip). Thank you

**Comment by kireevco** [comment]
@williamesp2015 Please provide more details what exactly is missing? Why don't you fork sming repo and add your changes to your fork. We can go from there?
zip file is not a very good idea.

**Comment by robotiko** [comment]
Duplicates #164 with specific code reference

**Comment by kireevco** [comment]
Closing in favour of #164
