### ISSUE TITLE
c:/tools/sming/Sming: Permission denied

### ISSUE THREAD

**Issue by crosofg** [anakod/Sming#204]
I am unable to make. I get this error.
makefile:20: c:/tools/sming/Sming: Permission denied. 
How do I get past this error?

**Comment by kireevco** [comment]
Can you please make sure you're running this as administrator?
What is your OS?

**Comment by crosofg** [comment]
I am using eclipse. How do I grant administrator privilege?
I am using Windows 10.

**Comment by crosofg** [comment]
changing  c:/Espressif to c:\Espressif helped.

**Comment by kireevco** [comment]
@crosofg Sounds good.

I create (Troubleshooting Windows)[https://github.com/anakod/Sming/wiki/Troubleshooting-Windows] wiki for future reference.
