### ISSUE TITLE
SDK 1.2 and 1.3

### ISSUE THREAD

**Issue by flexiti** [anakod/Sming#207]
File :  c:\tools\sming\Sming\compiler\ld\eagle.app.v6.cpp.ld should be changed for a new version of the SDK

eg. 

    _rodata_start = ABSOLUTE(.);
	*(.sdk.version)                             // is added
    *(.rodata)

**Comment by flexiti** [comment]
irom0_0_seg :                         org = 0x40209000, len = 0x42000   -  maybe also ?

**Comment by kireevco** [comment]
relates to https://github.com/anakod/Sming/issues/136. We need a proper git-flow,that no new features will break current release. @anakod it's time for [git-flow](http://nvie.com/posts/a-successful-git-branching-model/).
