### ISSUE TITLE
Websocket client

### ISSUE THREAD

**Issue by crosofg** [anakod/Sming#211]
How Do I initialize websocket client?
Camn someone share any sample code?

**Comment by kireevco** [comment]
@crosofg did you check https://github.com/anakod/Sming/tree/master/HttpServer_WebSockets ?

**Comment by crosofg** [comment]
yes. I have seen that. I wanted to create ws server on my desktop and create ws clinets on ESP. Is it possible?

**Comment by kireevco** [comment]
Unless I missed something I don't think we have a client yet. Why not use mqtt?

**Comment by crosofg** [comment]
I could use mqtt. I was just exploring other options.

**Comment by crosofg** [comment]
Can the header files be modified to include websocket clinet? What changes need to be done?
