### ISSUE TITLE
make: *** [out/firmware/spiff_rom.bin] Error 1

### ISSUE THREAD

**Issue by cartoonincm** [anakod/Sming#223]
i got form "HttpServer_WebSockets" only.
other example project work for me.
Can you help me to solve please.

Checking for spiffs files
files directory exists. Creating spiff_rom.bin
/bin/sh: spiffy: command not found
mv: rename spiff_rom.bin to out/firmware/spiff_rom.bin: No such file or directory
make: *** [out/firmware/spiff_rom.bin] Error 1

**Comment by anakod** [comment]
You should install spiffy

**Comment by cartoonincm** [comment]
how to install that?

**Comment by cartoonincm** [comment]
I found turtorial in "Linux QuickStart"
link this 
----------------------------------------------------------------------------------------------------------------------------------------
wget https://bintray.com/artifact/download/kireevco/generic/spiffy-linux-1.0.1.tar.gz
tar -zxf spiffy-linux-1.0.1.tar.gz && sudo mv spiffy /usr/local/bin/
sudo chmod +rx /usr/local/bin/spiffy
----------------------------------------------------------------------------------------------------------------------------------------

But i don't know about OS X

**Comment by kireevco** [comment]
@caquino Please try a prev. version from here: https://bintray.com/artifact/download/kireevco/generic/spiffy-1.0.3-macos-x86_64.tar.gz

I'll build 1.0.4 as soon as I can.

**Comment by piperpilot** [comment]
You can also clone spiffy from here:

https://github.com/alonewolfx2/spiffy.git

Create a build directory inside of the spiffy folder, run make, copy the spiffy executable to your /usr/bin/ directory and make sure it is executable.

**Comment by cartoonincm** [comment]
@piperpilot  wow wow now it worked thanks a lot

**Comment by piperpilot** [comment]
I will add these instructions to the OSX quick start.  Go ahead and close your issue if this is solved for you.

**Comment by cartoonincm** [comment]
in my side it worked every thing. thank you so much. :)

**Comment by anakod** [comment]
Great. I think we should improve our quick start guides and related information.
