### ISSUE TITLE
Invalid arguments in application.cpp

### ISSUE THREAD

**Issue by Airji3d** [anakod/Sming#234]
I get these errors when I build Basic_Blink (see picture attached).
The build and flash to ESP-01 worked and the led blinks but why these errors.

echo %ESP_HOME%
 c:\Espressif

echo %SMING_HOME%
 c:\tools\sming\Sming

echo %PATH%
C:\tools\mingw64\msys\1.0\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Fil
es (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Program Files\Common
 Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microso
ft Shared\Windows Live;C:\Program Files\Dell\DW WLAN Card;;c:\Program Files (x86
)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\
Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\
Program Files\WIDCOMM\Bluetooth Software\;c:\Program Files\WIDCOMM\Bluetooth Sof
tware\syswow64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Trend
 Micro\AMSP;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\chocolatey\bin;C:
\Program Files\Eclipse Foundation\4.4.2\eclipse;C:\Program Files\Java\jre1.8.0_5
1\bin;C:\tools\mingw64\msys\1.0\bin;

![eclipseblinkerrors](https://cloud.githubusercontent.com/assets/5619438/9501389/1f408184-4bf9-11e5-8f3e-02f615885a77.JPG)

Thanks in advance for the help, 
Rolland

**Comment by kireevco** [comment]
@Airji3d did you try building from a command line? `make` in your project directory?

**Comment by Airji3d** [comment]
Yes I did try make from command line in my projects folder and it builds with no error.
My question is how do I fix the project path for the includes not found?
Why the invalid arguments in the app.cpp?

Rolland

**Comment by kireevco** [comment]
Did you re-create eclipse workspace? (New Workspace)

--
Sincerely,
 Dmitry Kireev
 cel.: +1 (818) 850-5577
 email, gtalk: dmitry@kireev.co
<dmitry@kireev.co> skype: kireev.co
 aim: 336719228

**Comment by Airji3d** [comment]
No I didn't do that, I'll try it and reply.

**Comment by Airji3d** [comment]
Changed workspace and it removed the invalid path errors, thanks.
I still have the warnings
Invalid project path: Include path not found (\usr\include) etc.

Rolland

**Comment by Airji3d** [comment]
OK found that it was a bad Eclipse workspace metadata setup.
Thanks Dmitry.

**Comment by perttierkkila** [comment]
I have same error quite randomly. It seems to be problem with C/C++ Indexes. Make works fine.

Point the project, right-click, Index -> Rebuild did the trick for me to get rid of those "Invalid arguments"-errors.
