### ISSUE TITLE
Sming projects don't work separately from sming directory

### ISSUE THREAD

**Issue by kireevco** [anakod/Sming#24]
We need to find a way to build sming project (say Blink2) when it is located anywhere outside of Sming directory (say in ~/dev/Blink2 or in c:\User\Blink2).

**Comment by j0hncc** [comment]
Is there a way to "upvote" this  :)
:arrow_up:

**Comment by kireevco** [comment]
You just did:)

**Comment by ToSa27** [comment]
So this might be the reason why i wasn't able to setup a new project using Sming from scratch... I followed the steps provided with the DevKit for Windows and then tried to apply whatever is needed to get it working with sming (makefile adjusted for G++ / linking Sming / etc.)
Once this is fixed, it would be great to have e.g. an entry in the wiki describing the steps to create a new project in eclipse ready for sming development :)

**Comment by kireevco** [comment]
All, Please test my branch https://github.com/kireevco/sming/tree/crossplatform
Make sure to set SMING_HOME and ESP_HOME environment variables 
(see corresponding section in https://github.com/anakod/Sming/wiki/Windows-Quickstart & https://github.com/anakod/Sming/wiki/MacOS-Quickstart)
