### ISSUE TITLE
feature/rboot - Makefile-rboot.mk tweaks

### ISSUE THREAD

**Issue by gschmottlach** [anakod/Sming#269]
FYI -

Looking at Richard's Makefile-rboot.mk in the feature/rboot branch, I believe the following changes should be made. Specifically:

APP_AR	:= $(addprefix $(BUILD_BASE)/,$(TARGET).a)

Should be:

APP_AR	:= $(addprefix $(BUILD_BASE)/,$(TARGET)_app.a)

If you don't do this then all of the application code ends up in iram rather than irom where you'd expect it to be. See his rom0.ld linker file where app_app.a is placed in irom0.text but  APP_AR is named app.a. Either fix the Makefile-rboot.mk as suggested above or correct rom0.ld.

Also, when creating the SPIFFS file system the Makefile-rboot.mk calls "spiffy" directly assuming it's in the path. It would be more helpful/flexible if spiffy were represented by a Make variable (e.g. SPIFFY ?= spiffy) to make it easy to override the path to this application.

**Comment by raburton** [comment]
thanks, suggested changes made, pr created
