### ISSUE TITLE
Small error in "Install Sming Examples (optional)" Howto

### ISSUE THREAD

**Issue by fly3rman** [anakod/Sming#287]
>choco install sming.examples -y -source 'https://www.myget.org/F/kireevco-chocolatey/

Should be:
> choco install sming.examples -y -source 'https://www.myget.org/F/kireevco-chocolatey/'

The **'** is missing.

**Comment by raburton** [comment]
It's a wiki page, I assume anyone can edit it - it certainly let me. Fixed it for you.

**Comment by fly3rman** [comment]
Oh true, didn`t knew that. Thanks.
