### ISSUE TITLE
system restarting every 15 minutes.

### ISSUE THREAD

**Issue by alonewolfx2** [anakod/Sming#3]
it seems system have wdt issue.sming going to  wdt reset every 15 minutes. i tried wdt_feed but its not working. have you any idea?

**Comment by anakod** [comment]
Yes, I meet this problem, I think problem in SDK, not in Sming, but not sure.

**Comment by alonewolfx2** [comment]
normaly timers overflow every 35 minutes but it seems this value is 15 minutes in sming. we must to clear or disable wdt for stable working.

**Comment by anakod** [comment]
Disable WDT not good idea for stable working :)

**Comment by anakod** [comment]
I'm sure should be some simple fix for that. May be need to google more SDK WDT api.

**Comment by alonewolfx2** [comment]
can you join this chat https://gitter.im/alonewolfx2/Sming

**Comment by alonewolfx2** [comment]
it seems reboot problem resolved with this commit. https://github.com/anakod/Sming/commit/8c98f5db2ab637010b933379d382bbcc843062e6
