### ISSUE TITLE
mDNS support

### ISSUE THREAD

**Issue by MrZANE42** [anakod/Sming#37]
mDNS is quite nice on an IOT product.

Code (MIT licensed) can be found here:
https://github.com/n0bel/esp8266-mDNSResponder

Should be doable now the UDP works

**Comment by tprochazka** [comment]
Espressif has dirrect support for mDNS, it works quite easy, check the #79

**Comment by kireevco** [comment]
@anakod @tprochazka @MrZANE42 can this be closed?
