### ISSUE TITLE
SmingFramework (Sming Core) should be a library

### ISSUE THREAD

**Issue by kireevco** [anakod/Sming#45]
Sming should be a library (available for multiple platforms). That will allow us skip building Sming Core every time.

**Comment by alonewolfx2** [comment]
you are right. i think it can be very for compiling

**Comment by kireevco** [comment]
@alonewolfx2 what do we need to get a sming library? We need to SmingFramework.o and SmingFramework.h, that's it, rihgt?

**Comment by anakod** [comment]
I think if we will change Makefile to recursive compilation we can solve this problem: Project makes will ask Sming make, and include actual copy of library after first build.

**Comment by kireevco** [comment]
Work is going on here https://github.com/kireevco/Sming/tree/crossplatform2
Please test the branch
