### ISSUE TITLE
Add checks for conflicting environment

### ISSUE THREAD

**Issue by kireevco** [anakod/Sming#49]
Add checks for conflicting environment (cygwin, for instance)

**Comment by anakod** [comment]
About what this issue? Can you discover, please.

**Comment by kireevco** [comment]
Let's say if we are installing sming on a windows box that has cygwin or delphi and path contains wrong, incopatible toolset (make.exe, for example) - it won't let us to build anything properly (different version, older fork, etc.). I would like to check, if our environment is sane.

**Comment by j0hncc** [comment]
FYI I am finding that sming(mingw) AND my existing CYGWIN projects/environment does all work properly including eclipse once I settled on system path in this order:  c:\mingw\bin; c:\mingw\msys\1.0\bin ; c:\cygwin64

**Comment by kireevco** [comment]
thanks @j0hncc

**Comment by kireevco** [comment]
Closing for now. I'd rather move on to docker that will solve these issues by default
(https://github.com/kireevco/sming-docker)
