### ISSUE TITLE
Clarification on background magic

### ISSUE THREAD

**Issue by marvinroger** [anakod/Sming#76]
Hi, 

Thanks for this amazing project, a great push forward for the ESP8266 ecosystem.

However, I feel a little bit uncomfortable with how the Wifi stack and FTP server (for example) are handled. 
On Arduino for ESP8266, the Wifi stack is handled at each end of the loop function, or at an explicit yield or delay call if the loop function takes too long.
An FTP server would be init'ed in the setup function and would be kept alive with kind of a FTP.loop function in the Arduino loop function. This is a behaviour I understand, because I explicitely control it.

This is where I am lost: there is no such loop function, therefore no kind of FTP.loop function. Would you then please clarify the way Swing works? Is Swing event based only, so a blocking function call would block the whole thing (wifi, servers)?

Thanks.

**Comment by anakod** [comment]
Sming is working in asynchronous mode - it will call your callback when it needed. All other time ESP will process main tasks - WiFi network supporting and TCP stack processing.
